export const MAJORS = [
  'Computer Science',
  'Software Engineering',
  'Data Science',
  'Information Technology',
  'Computer Engineering',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Business Administration',
  'Economics',
  'Finance',
  'Marketing',
  'Mathematics',
  'Statistics',
  'Physics',
  'Chemistry',
  'Biology',
  'Psychology',
  'Design',
  'Information Systems',
  'Other'
];

export const SCHOOLS = [
  'Stanford University',
  'Massachusetts Institute of Technology (MIT)',
  'University of California, Berkeley',
  'Carnegie Mellon University',
  'University of Washington',
  'Georgia Institute of Technology',
  'University of Illinois Urbana-Champaign',
  'University of California, San Diego',
  'University of California, Los Angeles (UCLA)',
  'University of Southern California',
  'University of Texas at Austin',
  'University of Michigan',
  'Cornell University',
  'Harvard University',
  'Princeton University',
  'Yale University',
  'Columbia University',
  'University of Pennsylvania',
  'Duke University',
  'Northwestern University',
  'Other'
];

export const TARGET_ROLES = [
  'Software Engineer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Mobile Developer',
  'Data Scientist',
  'Data Analyst',
  'Machine Learning Engineer',
  'DevOps Engineer',
  'Site Reliability Engineer',
  'Product Manager',
  'Product Marketing Manager',
  'UX Designer',
  'UI Designer',
  'Product Designer',
  'Security Engineer',
  'Cloud Engineer',
  'Systems Engineer',
  'Research Scientist',
  'Software Development Engineer in Test',
  'Technical Program Manager',
  'Engineering Manager',
  'Other'
];

export const TARGET_INDUSTRIES = [
  'Technology',
  'Software',
  'Financial Services',
  'Banking',
  'Healthcare',
  'Biotechnology',
  'E-commerce',
  'Social Media',
  'Gaming',
  'Entertainment',
  'Media',
  'Education',
  'Consulting',
  'Automotive',
  'Aerospace',
  'Energy',
  'Real Estate',
  'Transportation',
  'Logistics',
  'Retail',
  'Telecommunications',
  'Cybersecurity',
  'Other'
];

export const TARGET_LOCATIONS = [
  'San Francisco, CA',
  'New York, NY',
  'Seattle, WA',
  'Austin, TX',
  'Boston, MA',
  'Los Angeles, CA',
  'Chicago, IL',
  'Denver, CO',
  'Atlanta, GA',
  'Miami, FL',
  'Washington, DC',
  'Portland, OR',
  'San Diego, CA',
  'Raleigh, NC',
  'Nashville, TN',
  'Remote',
  'Hybrid',
  'Other'
];